#+title: Notes

* Queer joy
Jag frågade folk vad queer joy betyder för dem, detta är svaren jag fick:
- Att få vara mig själv, precis på det sättet jag vill
- För mig är det att inte böva vara bunder av det cis-hetero-normative sättet att se på identitet och relationer
- Att vara udda, weird och olika, och andra respekterar det och låter sig själva vara hur än de är. Medkänsla mellan andra, och/eller mig själv
- Att få vara mig själv och bli accepterad och respejterad för det. Och att kunna vå med vem/vilka jag vill utan att någon ser ner på mig och mitt förhållande.
- Community. Knowing other people going through similar things and seeing them enjoy life.

Queer joy verkar handla om just att få vara queer och glad samtidigt, tillsammans med andra som också är queera och glada.
* Idéer
** något story baserat
** ett spel där man bara skuttar runt och kramar folk
** att hjälpa folk hitta och acceptera sig själva
*** att man ska hitta något item eller liknande och ge till folk?
*** Att man tar energier från en person och ger till en annan, a la Ni no Kuni
** skapa en queer commune som man måste värva folk in i
*** Så måste man ha rätt folk där för att kunna värva in någon ny
** ett detektiv-spel där man inte löser brott utan identiteter
** man befinner sig i en svartvit värld och att man kan sprida färger i olika prideflaggspaletter
*** Att man har en aura runt sig där man kan se queerhet eller liknande
** Någonting likt Speeddating for Ghosts
